### ISSUE TITLE
Python 3.9 deprecates function getiterator on ElementTree

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-rqt-gui#2]
According to [this issue](https://github.com/ros-visualization/rqt/issues/240), python3.9 changes getiterator function to iter in `/opt/ros/noetic/lib/python3.9/site-packages/rqt_gui/ros_plugin_provider.py`

**Comment by Maik93** [comment]
Thanks to both of you, you've just saved my day while debugging TF trees!

**Comment by aristizabal95** [comment]
I'm still having this issue, and changing `getiterator` to `iter` causes `segmentation fault` while `crawling for plugins of type 'qt_gui'`

**Comment by AchmadFathoni** [comment]
> I'm still having this issue, and changing `getiterator` to `iter` causes `segmentation fault` while `crawling for plugins of type 'qt_gui'`

Do you use other AUR repo mirror? like arch4edu?

**Comment by acxz** [comment]
Closed with 2f91da4
